# Generated by Django 2.2.14 on 2021-08-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='choice',
            field=models.CharField(choices=[('top_view', 'top_view'), ('best_sale', 'best_sale'), ('on_sale', 'on_sale'), ('hot_item', 'hot_item')], max_length=200),
        ),
    ]
