# Generated by Django 2.2.14 on 2021-08-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20210813_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='choice',
            field=models.CharField(choices=[('on_sale', 'on_sale'), ('top_view', 'top_view'), ('hot_item', 'hot_item'), ('best_sale', 'best_sale')], max_length=200),
        ),
    ]
