# Generated by Django 2.2.14 on 2021-08-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_auto_20210813_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='choice',
            field=models.CharField(blank=True, choices=[('on_sale', 'on_sale'), ('top_view', 'top_view'), ('best_sale', 'best_sale'), ('hot_item', 'hot_item')], max_length=200),
        ),
    ]
