# Generated by Django 2.2.14 on 2021-08-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20210813_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='choice',
            field=models.CharField(blank=True, choices=[('top_view', 'top_view'), ('best_sale', 'best_sale'), ('on_sale', 'on_sale'), ('hot_item', 'hot_item')], max_length=200),
        ),
    ]
