# Generated by Django 2.2.14 on 2021-08-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_auto_20210816_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='choice',
            field=models.CharField(blank=True, choices=[('top_view', 'top_view'), ('best_sale', 'best_sale'), ('hot_item', 'hot_item'), ('on_sale', 'on_sale')], max_length=200),
        ),
    ]
