# Generated by Django 2.2.14 on 2021-08-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_auto_20210819_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='choice',
            field=models.CharField(blank=True, choices=[('hot_item', 'hot_item'), ('top_view', 'top_view'), ('on_sale', 'on_sale'), ('best_sale', 'best_sale')], max_length=200),
        ),
    ]
