# Generated by Django 2.2.14 on 2021-08-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='choice',
            field=models.CharField(blank=True, choices=[('on_sale', 'on_sale'), ('best_sale', 'best_sale'), ('hot_item', 'hot_item'), ('top_view', 'top_view')], max_length=200),
        ),
    ]
