# Generated by Django 2.2.14 on 2021-08-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0016_auto_20210819_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='choice',
            field=models.CharField(blank=True, choices=[('best_sale', 'best_sale'), ('on_sale', 'on_sale'), ('hot_item', 'hot_item'), ('top_view', 'top_view')], max_length=200),
        ),
    ]
